# Generated by Django 2.1.7 on 2019-04-30 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('pin_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('std_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Enquiry', 'Enquiry'), ('Propect', 'Prospect'), ('Customer', 'Customer')], max_length=10)),
                ('company', models.CharField(max_length=200)),
                ('print_name', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('agent', models.CharField(blank=True, choices=[('Executive', 'Executive'), ('Collaborative', 'Collaborative'), ('Contributory', 'Contributory'), ('Communicative', 'Communicative'), ('Service', 'Service')], max_length=20, null=True)),
                ('broker', models.CharField(blank=True, choices=[('amd', 'amd'), ('BrokerTest', 'BrokerTest'), ('KLM', 'KLM'), ('Test', 'Test')], max_length=20, null=True)),
                ('registration_type', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Composition', 'Composition'), ('Consumer', 'Consumer'), ('Unregistered', 'Unregistered'), ('Unknown', 'Unknown')], max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('tax_type', models.CharField(choices=[('Local', 'Local'), ('Out-Station', 'Out-Station')], max_length=20)),
                ('vendor_code', models.CharField(blank=True, max_length=100, null=True)),
                ('party_type', models.CharField(blank=True, choices=[('Not Applicable', 'Not Applicable'), ('Deemed Export', 'Deemed Export'), ('Govt. Entry', 'Govt. Entry'), ('SEZ', 'SEZ')], max_length=10, null=True)),
                ('gstin_no', models.CharField(blank=True, max_length=15, null=True)),
                ('adhar_no', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=15, null=True)),
                ('dl_no', models.CharField(blank=True, max_length=15, null=True)),
                ('other', models.CharField(blank=True, max_length=15, null=True)),
                ('gstin_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('adhar_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('pan_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('dl_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('other_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(blank=True, choices=[('Proprietary', 'Proprietary'), ('Partnership', 'Partnership'), ('Pvt. Ltd. Company', 'Pvt. Ltd. Company'), ('Public Ltd', 'Public Ltd')], max_length=15, null=True)),
                ('investment', models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=15, null=True)),
                ('establishment_year', models.IntegerField(blank=True, null=True)),
                ('certification', models.TextField(blank=True, max_length=500, null=True)),
                ('credit_days', models.IntegerField(blank=True, null=True)),
                ('credit_limit', models.CharField(blank=True, max_length=20, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('page_no', models.IntegerField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, max_length=500, null=True)),
                ('brunch', models.CharField(blank=True, max_length=30, null=True)),
                ('account_no', models.CharField(blank=True, max_length=18, null=True)),
                ('isfc', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_address', models.TextField(blank=True, max_length=200, null=True)),
                ('document_heading', models.CharField(blank=True, max_length=20, null=True)),
                ('docket_category', models.CharField(blank=True, max_length=20, null=True)),
                ('docket_description', models.TextField(blank=True, max_length=200, null=True)),
                ('docket_file', models.FileField(blank=True, null=True, upload_to='')),
                ('delivery_contact', models.CharField(blank=True, max_length=30, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_address', models.TextField(blank=True, max_length=500, null=True)),
                ('delivery_mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('delivary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('person_name', models.CharField(blank=True, max_length=30, null=True)),
                ('person_department', models.CharField(blank=True, max_length=30, null=True)),
                ('person_mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Area')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Bank')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('pattern', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('unit_size', models.CharField(blank=True, max_length=500, null=True)),
                ('product_type', models.CharField(blank=True, choices=[('Finish', 'Finish'), ('Raw', 'Raw'), ('Scrap', 'Scrap'), ('Semi-finish', 'Semi-finish')], max_length=100, null=True)),
                ('sale_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode_img', models.ImageField(blank=True, null=True, upload_to='media')),
                ('discount', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=100)),
                ('deal', models.CharField(choices=[('both', 'both'), ('sale', 'sale'), ('purchase', 'purchase')], max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Category')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Design')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('pin_code', models.IntegerField()),
                ('address', models.TextField(max_length=1000)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=200)),
                ('gst_no', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.ForeignKey(on_delete=None, to='master.City')),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('end_use', models.CharField(blank=True, max_length=200, null=True)),
                ('fabric_type', models.CharField(blank=True, max_length=200, null=True)),
                ('color_fastness', models.CharField(blank=True, max_length=200, null=True)),
                ('composition', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('instruction', models.TextField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('state_code', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Country')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='state',
            field=models.ForeignKey(on_delete=None, to='master.State'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Manufacturer'),
        ),
        migrations.AddField(
            model_name='item',
            name='shade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Shade'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Unit'),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.State'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.City'),
        ),
        migrations.AddField(
            model_name='area',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Country'),
        ),
        migrations.AddField(
            model_name='area',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.State'),
        ),
        migrations.AddField(
            model_name='area',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
