# Generated by Django 2.1.7 on 2019-06-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20190605_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='certification',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
