# Generated by Django 2.1.7 on 2019-06-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20190605_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='certification',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='remark',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
