# Generated by Django 2.1.7 on 2019-06-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20190605_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='delivary_email',
            new_name='delivery_email',
        ),
    ]
