# Generated by Django 2.1.7 on 2019-06-12 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0005_auto_20190605_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('rate', models.CharField(max_length=20)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=None, to='master.Customer')),
                ('product', models.ForeignKey(on_delete=None, to='master.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
